version: '3'

services:
  mysql: #Service 1: Database
    image: 'mysql:latest'
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=pmapp21
      - MYSQL_DATABASE=PMSystemFinalDB
      - MYSQL_USER=pmapp
      - MYSQL_PASSWORD=mlapp21

  api: #Service 2: .Net Server
    restart: on-failure
    build:
      context: ./Python-Server
      dockerfile: Dockerfile
    environment:
      - DB_HOST=mysql
      - DB_NAME=maarbeit
      - DB_USER=mlapp
      - DB_PASSWORD=mlapp21
    depends_on:
      - mysql
    links:
      - mysql